-- Q1. What is the total revenue generated by male vs. female customers?

select gender,sum(purchase_amount) from customer_data
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount from customer_data
where discount_applied = 'yes' and purchase_amount >= (select AVG(purchase_amount) from customer_data);

-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, round(avg(review_rating),2) from customer_data
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average purchase amounts between Standard and Express shipping.

select shipping_type, round(avg(purchase_amount),2) as 'avg_purchase' from customer_data
where shipping_type in ('standard', 'Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare the average spend and total revenue between subscribers and non-subscribers.

select subscription_status, 
round(avg(purchase_amount),2) as 'avg purchase',
count(customer_id) as "n of cust",
sum(purchase_amount) as 'tot rev' from customer_Data
group by subscription_status 
order by 'tot rev' desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased, 
ROUND(sum(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 end)*100/COUNT(*),2) as 'discount'FROM customer_data
group by item_purchased
order by discount desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases.

with customer as(
select customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases between 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END 
    AS customer_segment FROM customer_data
)

select customer_segment, count(*) as 'n of customers' from customer
group by customer_segment;



-- Q8. What are the top 3 most purchased products within each category?

with item_count as  (
	select category, 
    item_purchased, 
    count(customer_id) as 'N_of_customers',
    row_number() OVER(PARTITION BY category order by count(customer_id)) as 'Item_rank' from customer_data
    group by category, item_purchased
)
select category, item_purchased, N_of_customers,Item_rank from item_count
    where Item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases)
-- also likely to subscribe?

select subscription_status, count(customer_id) as n_of_customers  from customer_data
where previous_purchases > 5 
group by subscription_status;

-- Q10. What is the revenue contribution of each age group?

select age_group,sum(purchase_amount)  as total_spend from customer_data
group by age_group
order by total_spend desc;